### PR TITLE
enable ingress controller and disable adservice monitoring

### PR DESCRIPTION
**Pull request by rogercoll**
# Changes

Required modifications:

```
  Change the host to point your IP or public dns: otel-demo.104.197.4.188.nip.io
```

Required commands:  

```
// install the nginx ingress controller
$ helm install --namespace kube-system nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx
// install the demo helm chart with the ingress extension
$ helm install -f deployment.yaml -f deployment_ingress.yaml my-otel-demo open-telemetry/opentelemetry-demo
```

## Merge Requirements

For new features contributions, please make sure you have completed the following
essential items:

* [ ] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]
* [ ] Appropriate Helm chart updates in the [helm-charts][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Review by andrewvc — COMMENTED** [review]
Can we add  commands listed in the PR description to the README?

**Comment by rogercoll** [comment]
> Can we add commands listed in the PR description to the README?

Definitely, but I think we should first decide what is the scope of these changes:

- Do we want to enable the ingress route + disable some service with the same configuration file?  What should be the name of this file? Which description we should provide in the README? I reckon it would be the best if we explain the reasoning behind explicitly disabling the corresponding services.
  - Maybe documented under a README section named "RCA workshop"?
- Do we know which services we want to disable for the RCA workshop?

@andrewvc

**Comment by jasonrhodes** [comment]
Thanks, @rogercoll -- @LucaWintergerst has put together [a gist of the workshop modifications we'd like](https://gist.github.com/LucaWintergerst/160043e393e5754fd493b9d80673e830#file-deployment-yaml-L77-L83) (it's the entire deployment.yaml with changes made, not sure if that's best or just having a separate file with changes only), but without the change above re: the ingress controller. 

And yes, we should either move this to a branch or explicitly mark it as RCA workshop or similar.

**Comment by rogercoll** [comment]
> not sure if that's best or just having a separate file with changes only

I would suggest better using two files if possible, the second file that we provide for the RCA workshop should only contain the changes for this specific environment. That way we benefit from the main file maintained configuration too (in case we add new envs, extended collector config, etc.).

> @rogercoll I'm also not super familiar with nip.io—the idea is that each engineer needs to modify the yaml file and change that hostname to include their own public IP?

Exactly, basically by using nip.io (I guess there are other public similar services) you avoid having to modify your `hosts` file, it should work for private ip addresses too (I think we can remove it and just rely on mofing the hosts file). This PR was filled just to showcase the enablement of the demo's ingress controller, but please feel free to open a new one if it's easier for you to contribute these changes.

**Comment by rogercoll** [comment]
If it works for you, I would close this PR in favor of this branch: https://github.com/elastic/opentelemetry-demo/tree/rca_ingress_obs

**Pull request closed without merging**
